### ISSUE TITLE
Intermittent problem w/ the new optimized InstanceKey

### ISSUE THREAD

**Issue by jeremydmiller** [structuremap/structuremap#365]
See this error from FubuMVC testing:

It's happening maybe 1 in a hundred times, but enough to be a severe problem. Fix.

```

Finished running task health monitoring on node Node1
7f62016e-d45c-4bee-8d0f-1645f31b26e2
TakeOwnershipRequest for subject: scheduled://jobs/
StructureMap.Building.StructureMapBuildException: Error while building type FubuMVC.Core.ServiceBus.Async.AsyncHandlingBehavior.  See the inner exception for details
1.) new AsyncHandlingBehavior(*Default of IAsyncHandling*){
    Set IActionBehavior InsideBehavior = Lifecycle resolution of CascadingAsyncHandlerInvoker<MonitoringControlHandler, TakeOwnershipRequest, TakeOwnershipResponse> ('df73f6a9-dc8b-4789-bbf9-d0fe4019681c')
}
2.) FubuMVC.Core.ServiceBus.Async.AsyncHandlingBehavior ('84ae3453-460d-4a3e-81a5-7d4a644cd53f')
3.) Instance of FubuMVC.Core.Behaviors.IActionBehavior ('84ae3453-460d-4a3e-81a5-7d4a644cd53f')
4.) new ExceptionHandlerBehavior(Lifecycle resolution of FubuMVC.Core.ServiceBus.Async.AsyncHandlingBehavior ('84ae3453-460d-4a3e-81a5-7d4a644cd53f'), Value: FubuMVC.Core.ServiceBus.ErrorHandling.ExceptionHandlerNode --> FubuMVC.Core.ServiceBus.Asy
5.) FubuMVC.Core.ServiceBus.ErrorHandling.ExceptionHandlerBehavior ('3c5c32e5-4b8f-4862-b0ed-0a5ed2df798d')
6.) Instance of FubuMVC.Core.Behaviors.IActionBehavior (FubuMVC.Core.ServiceBus.ErrorHandling.ExceptionHandlerBehavior)
7.) Container.GetInstance(FubuMVC.Core.Behaviors.IActionBehavior, '3c5c32e5-4b8f-4862-b0ed-0a5ed2df798d')
 ---> System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at StructureMap.Pipeline.Instance.InstanceKey(Type pluginType) in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\Pipeline\Instance.cs:line 204
   at StructureMap.Pipeline.LifecycleObjectCache.Get(Type pluginType, Instance instance, IBuildSession session) in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\Pipeline\LifecycleObjectCache.cs:line 51
   at lambda_method(Closure , IBuildSession , IContext )
   --- End of inner exception stack trace ---
   at lambda_method(Closure , IBuildSession , IContext )
   at StructureMap.Building.BuildPlan.Build(IBuildSession session, IContext context) in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\Building\BuildPlan.cs:line 151
   at StructureMap.Pipeline.LifecycleObjectCache.Get(Type pluginType, Instance instance, IBuildSession session) in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\Pipeline\LifecycleObjectCache.cs:line 71
   at StructureMap.SessionCache.GetObject(Type pluginType, Instance instance, ILifecycle lifecycle) in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\SessionCache.cs:line 93
   at StructureMap.Container.GetInstance(Type pluginType, String instanceKey) in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\Container.cs:line 240
   at StructureMap.Container.GetInstance[T](String instanceKey) in c:\BuildAgent\work\a395dbde6b793293\src\StructureMap\Container.cs:line 76
   at FubuMVC.Core.StructureMap.NestedStructureMapContainerBehavior.StartInnerBehavior() in c:\code\fubumvc\src\FubuMVC.Core\StructureMap\NestedStructureMapContainerBehavior.cs:line 36
   at FubuMVC.Core.StructureMap.NestedStructureMapContainerBehavior.Invoke() in c:\code\fubumvc\src\FubuMVC.Core\StructureMap\NestedStructureMapContainerBehavior.cs:line 26
   at FubuMVC.Core.ServiceBus.Runtime.Invocation.ChainInvoker.ExecuteChain(Envelope envelope, HandlerChain chain) in c:\code\fubumvc\src\FubuMVC.Core\ServiceBus\Runtime\Invocation\ChainInvoker.cs:line 67
   at FubuMVC.Core.ServiceBus.Runtime.Invocation.ChainExecutionEnvelopeHandler.ExecuteChain(Envelope envelope, HandlerChain chain) in c:\code\fubumvc\src\FubuMVC.Core\ServiceBus\Runtime\Invocation\ChainExecutionEnvelopeHandler.cs:line 42
Opening up a new in memory RavenDb IDocumentStore at


```

**Comment by DixonD-git** [comment]
Looks like a problem with concurrency. When I did the pull request #356 , I assumed for some reason that `InstanceKey` should not be used in concurrent matter. I will check again, and if it is not the case, I will fix it by using `ConcurrentDictionary` instead.
