### ISSUE TITLE
Help please: Null reference exception in StructureMap brought down our production site

### ISSUE THREAD

**Issue by shaulbehr** [structuremap/structuremap#514]
Hi,
We had a pretty major crisis today; our production API servers went down.  Any API that was called resulted in the following error message being written to our logs:

```
2016-10-18 17:45:18,048 ERROR Logger [host=ip-0A5A0A4C:appdomain=/LM/W3SVC/1/ROOT-1-131212332110285046:referenceid=2fdc280b-777a-42c7-9353-851ba808a509] -  An unhandled exception occurred in the OWIN Pipeline while processing request: http://10.90.10.76/api/StatusCheck?key=72B917EF-378A-4CAB-891D-ADF090633E0D

System.NullReferenceException: Object reference not set to an instance of an object.
   at StructureMap.Container.GetNestedContainer() in c:\BuildAgent\work\996e173a8ceccdca\src\StructureMap\Container.cs:line 538
   at DependencyResolution.Api.Middleware.StructureMapMiddleware.<Invoke>d__2.MoveNext() in D:\Bamboo\xml-data\build-dir\API-R4V13-JOB1srcDependencyResolutionApiMiddlewareStructureMapMiddleware.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DependencyResolution.Api.Middleware.ExceptionHandlerMiddleware.<Invoke>d__3.MoveNext() in D:\BaDboo\xml-data\build-dir\API-R4V13-JOB1\JOB1srcDependencyResolutionApiMiddlewareExceptionHandlerMiddleware.cs 30
```

Line 21 of StructureMapMiddleware is this:

```
            using (var nestedContainer = _container.GetNestedContainer())
```

It should be noted that nothing new was deployed today; the version of code in production has been working fine for the last 5 days.  But suddenly today, under peak load conditions, everything failed.
We recovered simply by restarting IIS on our API servers.  But now we are spooked as allgetout, because this kind of random stuff could happen anytime.

Any ideas as to how getting a nested container could result in a null reference exception?
The version of StructureMap on our production build is 3.1.4.143

Many thanks in advance for your assistance!

**Comment by jeremydmiller** [comment]
@shaulbehr *Something* disposed the main application container in your application is my guess. We got much better error messages and even a "DisposalLock" feature in newer versions of StructureMap for that kind of thing. Might wanna look for any class that injects `IContainer` directly maybe and accidentally disposes it.

**Comment by shaulbehr** [comment]
@jeremydmiller Thanks, sounds like a good idea to upgrade.  How do you use the DisposalLock?

**Comment by jeremydmiller** [comment]
Going to close this one since there's essentially a duplicate issue #517
