### ISSUE TITLE
NullReferenceException in LightweightCache

### ISSUE THREAD

**Issue by DixonDs** [structuremap/structuremap#573]
This happened during heavy multi-threading testing:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. ---> StructureMap.StructureMapBuildPlanException: Error while trying to create the BuildPlan for Instance of StructureMap.Testing.Performance.TypeCatalog+IService1 -- StructureMap.Testing.Performance.TypeCatalog+Service1.
Please check the inner exception
1.) Container.GetInstance(StructureMap.Testing.Performance.TypeCatalog+IService1)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at StructureMap.Util.LightweightCache`2.get_Item(TKey key) in C:\OSS\structuremap\src\StructureMap.Testing.Performance.SM4Last\SM4Container.cs:line 0
   at StructureMap.Building.TryCatchWrapper.wrap[T](String message, Type returnType, Expression expression, Expression description) in C:\OSS\structuremap\src\StructureMap.Testing.Performance.SM4Last\SM4Container.cs:line 0
   at StructureMap.Building.TryCatchWrapper.WrapFunc[T](String message, Type returnType, Expression expression, IDescribed described) in C:\OSS\structuremap\src\StructureMap.Testing.Performance.SM4Last\SM4Container.cs:line 0
   at StructureMap.Building.ConcreteBuild.ToExpression(ParameterExpression session, ParameterExpression context) in C:\OSS\structuremap\src\StructureMap.Testing.Performance.SM4Last\SM4Container.cs:line 0
   at StructureMap.Building.BuildPlan.ToDelegate() in C:\OSS\structuremap\src\StructureMap.Testing.Performance.SM4Last\SM4Container.cs:line 0
   at StructureMap.Building.BuildPlan..ctor(Type pluginType, Instance instance, IDependencySource inner, Policies policies, IEnumerable`1 interceptors) in C:\OSS\structuremap\src\StructureMap.Testing.Performance.SM4Last\SM4Container.cs:line 0
   at StructureMap.Pipeline.Instance.buildPlan(Type pluginType, Policies policies) in C:\OSS\structuremap\src\StructureMap.Testing.Performance.SM4Last\SM4Container.cs:line 0
   --- End of inner exception stack trace ---
   at StructureMap.Pipeline.Instance.buildPlan(Type pluginType, Policies policies) in C:\OSS\structuremap\src\StructureMap.Testing.Performance.SM4Last\SM4Container.cs:line 0
   at StructureMap.Pipeline.Instance.ResolveBuildPlan(Type pluginType, Policies policies) in C:\OSS\structuremap\src\StructureMap.Testing.Performance.SM4Last\SM4Container.cs:line 0
   at StructureMap.BuildSession.BuildNewInSession(Type pluginType, Instance instance) in C:\OSS\structuremap\src\StructureMap.Testing.Performance.SM4Last\SM4Container.cs:line 0
   at StructureMap.Pipeline.NulloTransientCache.Get(Type pluginType, Instance instance, IBuildSession session) in C:\OSS\structuremap\src\StructureMap.Testing.Performance.SM4Last\SM4Container.cs:line 0
   at StructureMap.BuildSession.ResolveFromLifecycle(Type pluginType, Instance instance) in C:\OSS\structuremap\src\StructureMap.Testing.Performance.SM4Last\SM4Container.cs:line 0
   at StructureMap.SessionCache.GetObject(Type pluginType, Instance instance, ILifecycle lifecycle) in C:\OSS\structuremap\src\StructureMap.Testing.Performance.SM4Last\SM4Container.cs:line 0
   at StructureMap.SessionCache.GetDefault(Type pluginType, IPipelineGraph pipelineGraph) in C:\OSS\structuremap\src\StructureMap.Testing.Performance.SM4Last\SM4Container.cs:line 0
   at StructureMap.Container.GetInstance(Type pluginType) in C:\OSS\structuremap\src\StructureMap.Testing.Performance.SM4Last\SM4Container.cs:line 0
```

**Comment by DixonDs** [comment]
I cannot reproduce it after https://github.com/structuremap/structuremap/pull/574
