### ISSUE TITLE
Structuremap somehow picking generated static constructor (due to static lambda) 

### ISSUE THREAD

**Issue by NinoFloris** [structuremap/structuremap#582]
Structuremap somehow picks the static constructor of a class it is constructing which results in       
```
System.ArgumentException : The constructor should not be static
``` 

This is at the `new` expression node inside ConstructorStep

Removing the static keyword from our lambda property circumvents the problem as the compiler won't generate a static constructor anymore then.

The lambda can be anything and the issue also shows with something silly like
```cs
private static Func<int, int> Identity { get; } = i => i;
```

I'm still trying to make a little repro but sadly enough it really won't show itself there, yet. At least it's very consistent in our big project.

**Comment by DixonDs** [comment]
Yes, a repro would be great. But can you at least paste the full stacktrace of the exception you get?

**Comment by NinoFloris** [comment]
Here it is, thanks for the quick reply.

```
---------------- StructureMap.StructureMapBuildPlanException : Error while trying to create the BuildPlan for Instance of Example<A, B> -- Example<A, B>.
      Please check the inner exception
      1.) new Converter`1(*Default of Example<A, B>*)
      2.) Converter<From>
      3.) Instance of Converter<From>

      -------------------- System.ArgumentException : The constructor should not be static
      Parameter name: constructor
      Stack Trace:
      ##our code##
        ----- Inner Stack Trace -----
           at lambda_method(Closure , IBuildSession , IContext )
           at StructureMap.Building.BuildPlan.Build(IBuildSession session, IContext context)
           at StructureMap.BuildSession.BuildNewInSession(Type pluginType, Instance instance)
           at StructureMap.Pipeline.NulloTransientCache.Get(Type pluginType, Instance instance, IBuildSession session)
           at StructureMap.BuildSession.ResolveFromLifecycle(Type pluginType, Instance instance)
           at StructureMap.SessionCache.GetObject(Type pluginType, Instance instance, ILifecycle lifecycle)
           at StructureMap.SessionCache.GetDefault(Type pluginType, IPipelineGraph pipelineGraph)
           at StructureMap.BuildSession.GetInstance(Type pluginType)
           at AutoMapper.MappingOperationOptions`2.CreateInstance[T]()
           at lambda_method(Closure , Object , Object , ResolutionContext )
        ----- Inner Stack Trace -----
           at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
           at StructureMap.Building.ConstructorStep.ToExpression(ParameterExpression session, ParameterExpression context)
           at StructureMap.Building.ConcreteBuild.buildInnerExpression(ParameterExpression session, ParameterExpression context)
           at StructureMap.Building.ConcreteBuild.ToExpression(ParameterExpression session, ParameterExpression context)
           at StructureMap.Building.BuildPlan.ToDelegate()
           at StructureMap.Building.BuildPlan..ctor(Type pluginType, Instance instance, IDependencySource inner, Policies policies, IEnumerable`1 interceptors)
           at StructureMap.Pipeline.Instance.buildPlan(Type pluginType, Policies policies)
```

**Comment by NinoFloris** [comment]
Adding some debug symbols gave me this result inside of ConstructorStep
![screen shot 2017-06-26 at 17 13 20](https://user-images.githubusercontent.com/4218809/27554839-1abc8cbc-5ab0-11e7-8499-61ce944f370c.png)

![screen shot 2017-06-26 at 17 13 53](https://user-images.githubusercontent.com/4218809/27554804-fc9122c0-5aaf-11e7-9307-ff61613eaac7.png)

How does a "constructor" that is not even marked true for `IsConstructor` end up inside your code? Is this a runtime issue? As I only see you using normal GetConstructors type of reflection calls I leave that verdict up to you as you of course have more intimate knowledge of the codebase.

**Comment by jeremydmiller** [comment]
@NinoFloris I don't have a clue. I'm afraid I'd have to see repro steps to help on this one.

**Comment by NinoFloris** [comment]
F yes, took another stab at this by slowly shutting more and more of our codebase's container inits/ registry loads etc down until I finally got an exact point which stopped the exception from appearing.

Then after some more pruning for a repro I have a solid root cause:
https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection/blob/1ad66e5c5a623fc54f84c1243051c8c9e80c396c/src/StructureMap.Microsoft.DependencyInjection/AspNetConstructorSelector.cs#L14

I'm working on a PR for correctly filtering out private and static constructors as we speak.

Too bad there doesn't seem to be a way to remove/override policies once they're registered, makes it harder to do a temp workaround.
https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection/blob/1ad66e5c5a623fc54f84c1243051c8c9e80c396c/src/StructureMap.Microsoft.DependencyInjection/ContainerExtensions.cs#L40

MS should state much more clearly that DeclaredConstructors includes static constructors, as they are so rarely included/useful for reflection/known about, this is basically a landmine waiting to explode now. I'll see what I can do about that.

Repro:
https://github.com/NinoFloris/structuremaprepro582

Thank you gentlemen, it was a pleasure.
