### ISSUE TITLE
StructureMap.Pipeline.Instance InstanceKey(Type pluginType) throws NullReferenceException when passed generic type

### ISSUE THREAD

**Issue by MrGlenThomas** [structuremap/structuremap#584]
I am using StructureMap.Microsoft.DependencyInjection in ASP.NET Core Web API and when I call app.ApplicationServices.GetServices(Type serviceType) with a generic type a NullReferenceException is thrown. It works ok with non-generic types.

Stack trace:
```
   at StructureMap.Pipeline.Instance.<>c__DisplayClass30_0.<InstanceKey>b__0(Type t)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at StructureMap.SessionCache.GetObject(Type pluginType, Instance instance, ILifecycle lifecycle)
   at StructureMap.SessionCache.GetDefault(Type pluginType, IPipelineGraph pipelineGraph)
   at StructureMap.Container.GetInstance(Type pluginType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetServices(IServiceProvider provider, Type serviceType)
   at Glen.ShoppingList.Api.Startup.Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory, ShoppingListIdentityInitializer shoppingListIdentityInitializer, IContainer container) in C:\Source\CheckoutShoppingList\source\Glen.ShoppingList.Api\Startup.cs:line 195
```

Example:

`app.ApplicationServices.GetServices(typeof(ICommandHandler<>))`

**Comment by jeremydmiller** [comment]
@MrGlenThomas StructureMap can't resolve open generic types, that's just not a valid use case.
