### ISSUE TITLE
NullReferenceException on GetProfile

### ISSUE THREAD

**Issue by DixonDs** [structuremap/structuremap#593]
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at StructureMap.Container.<>c.<CorrectSingletoneLifecycleForChild>b__45_0(Instance x)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at StructureMap.StringExtensions.Each[T](IEnumerable`1 enumerable, Action`1 action)
   at StructureMap.Container.CorrectSingletoneLifecycleForChild(IPipelineGraph pipelineGraph)
   at StructureMap.Container.GetProfile(String profileName)
```
I don't have a repro yet - we restarted the services where it was happenning and it seemed to help.

**Comment by NinoFloris** [comment]
Could be because Profiles is only created for a root PluginGraph and not guarded for null on child containers

https://github.com/structuremap/structuremap/blob/6c383cabc1cace084139030b8a253f4fd9a4ad2e/src/StructureMap/Graph/PluginGraph.cs#L74

**Comment by DixonDs** [comment]
@NinoFloris Could you elaborate? I am not sure I follow.

**Comment by DixonDs** [comment]
Another related, I believe, error, that we've seen in logs:
```
Message: System.ArgumentException: Destination array is not long enough to copy all the items in the collection. Check array index and length.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.ValueCollection.CopyTo(TValue[] array, Int32 index)
   at StructureMap.Util.LightweightCache`2.GetAll()
   at StructureMap.ComplexInstanceGraph.<>c.<ImmediateInstances>b__16_0(PluginFamily x)
   at System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at StructureMap.StringExtensions.Each[T](IEnumerable`1 enumerable, Action`1 action)
   at StructureMap.Container.CorrectSingletoneLifecycleForChild(IPipelineGraph pipelineGraph)
   at StructureMap.Container.GetProfile(String profileName)
```

This one looks like a concurrency issue to me judging from the `LightweightCache.GetAll` implementation.

**Comment by DixonDs** [comment]
So, yes, now I am certain it is a plain old concurrency issue. The following test fails pretty reliably:
```
[Fact]
public void GetProfileStressTest()
{
    const int profileCount = 5;
    var profileNames = Enumerable.Range(0, profileCount).Select(_ => Guid.NewGuid().ToString()).ToList();
    var container = new Container(cfg =>
    {
        foreach (var profileName in profileNames)
        {
            cfg.Profile(profileName, _ => { });
        }
    });

    Parallel.For(0, 10000, i =>
    {
        container.GetProfile(profileNames[i % profileCount]);
    });
}
```
