### ISSUE TITLE
Inconsistent DecorateAllWith behavior when using factories

### ISSUE THREAD

**Issue by Pvlerick** [structuremap/structuremap#599]
I'm having trouble getting my head around the behavior of DecorateAllWith.

```csharp
[Fact]
public void DecorateAllWith_Works1()
{
	var registry = new Registry();

	registry.For<IService>().DecorateAllWith<ServiceDecorator>();
	registry.For<IService>().Use(() => new Service());

	var container = new Container(registry);

	Assert.IsType(typeof(ServiceDecorator), container.GetInstance<IService>());
}

[Fact]
public void DecorateAllWith_Works2()
{
	var registry = new Registry();

	registry.For(typeof(IService)).DecorateAllWith(typeof(ServiceDecorator));
	registry.For<IService>().Use(() => new Service());

	var container = new Container(registry);

	Assert.IsType(typeof(ServiceDecorator), container.GetInstance<IService>());
}

[Fact]
public void DecorateAllWith_Fails1()
{
	var registry = new Registry();

	registry.For<IService>().DecorateAllWith<ServiceDecorator>();
	registry.For(typeof(IService)).Use(_ => new Service());

	var container = new Container(registry);

	Assert.IsType(typeof(ServiceDecorator), container.GetInstance<IService>());
}

[Fact]
public void DecorateAllWith_Fails2()
{
	var registry = new Registry();

	registry.For(typeof(IService)).DecorateAllWith(typeof(ServiceDecorator));
	registry.For(typeof(IService)).Use(_ => new Service());

	var container = new Container(registry);

	Assert.IsType(typeof(ServiceDecorator), container.GetInstance<IService>());
}

interface IService { }
class Service : IService { }
class ServiceDecorator : IService
{
	public ServiceDecorator(IService inner) { }
}
```

The two failing tests report the same exception: ```Message: System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: ReturnedType System.Object cannot be cast to the Interceptor Accepts type ```

**Comment by jeremydmiller** [comment]
Okay, so, what version, can you put the entire stack trace in please, and are you up for doing a pull request to address the validation logic if it really is some kind of SM bug?

**Comment by Pvlerick** [comment]
Version is ```4.5.0```

Full stack trace:
```
Result StackTrace:	
at StructureMap.Pipeline.Instance.AddInterceptor(IInterceptor interceptor)
   at StructureMap.StringExtensions.Each[T](IEnumerable`1 enumerable, Action`1 action)
   at StructureMap.InterceptionPolicy.Apply(Type pluginType, Instance instance)
   at StructureMap.Policies.<>c__DisplayClass10_0.<Apply>b__1(IInstancePolicy policy)
   at StructureMap.StringExtensions.Each[T](IEnumerable`1 enumerable, Action`1 action)
   at StructureMap.Policies.Apply(Type pluginType, Instance instance)
   at StructureMap.Pipeline.Instance.ApplyAllPolicies(Type pluginType, Policies policies)
   at StructureMap.PipelineGraph.DetermineLifecycle(Type pluginType, Instance instance)
   at StructureMap.SessionCache.GetDefault(Type pluginType, IPipelineGraph pipelineGraph)
   at StructureMap.Container.GetInstance[T]()
   at StructureMap.Microsoft.DependencyInjection.Tests.StructureMapContainerTests.DecorateAllWith_Fails1() in C:\Users\pvl\Documents\GitHub\StructureMap.Microsoft.DependencyInjection\test\StructureMap.Microsoft.DependencyInjection.Tests\StructureMapContainerTests.cs:line 72
Result Message:	
System.ArgumentOutOfRangeException : Specified argument was out of the range of valid values.
Parameter name: ReturnedType System.Object cannot be cast to the Interceptor Accepts type StructureMap.Microsoft.DependencyInjection.Tests.StructureMapContainerTests+IService
```

As for being ready for a PR, I'm not familiar with the code base at all but why not. Initially I'd like to know if this indeed some kind of bug or if I missed something with ```DecorateAllWith``` and its usage, if it is then I'd be happy to have a look.

(I found this and initially filing it [here](https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection/issues/35))
