### ISSUE TITLE
Looking for help, Don't understand error

### ISSUE THREAD

**Issue by stvndall** [structuremap/structuremap#638]
Hi there, 
I've been using structure map for a while, in dotnet core. And suddenly I have started getting some strange errors.

The 2 isolated packed I seem to be getting them from are 
Dapper (V 1.50.4) ---> this error was resolved by rolling back to V1.50.2
Grpc(V1.9.0) --> I have no current resolution to solve this.

I understand that this error is looking like it's originating from the dotnet framework itself, But I'm not sure if there is context I need to understand from Structuremap side. 

99% chance I'm doing something _stupid_ that is causing this.

I'm using dotnet Framework 2.0.3 and tried 2.1.4 with no change.

```
Parameter name: type) (Value cannot be null.
Parameter name: type) ---> System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
   at StructureMap.TypeRules.TypeExtensions.IsConcrete(Type type)
   at StructureMap.TypeRules.TypeExtensions.<rawFindInterfacesThatCloses>d__16.MoveNext()
   at StructureMap.TypeRules.TypeExtensions.<rawFindInterfacesThatCloses>d__16.MoveNext()
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at StructureMap.Graph.GenericConnectionScanner.<ScanTypes>b__5_0(Type type)
   at StructureMap.StringExtensions.Each[T](IEnumerable`1 enumerable, Action`1 action)
   at StructureMap.Graph.GenericConnectionScanner.ScanTypes(TypeSet types, Registry registry)
   at StructureMap.StringExtensions.Each[T](IEnumerable`1 enumerable, Action`1 action)
   at StructureMap.Graph.AssemblyScanner.<ScanForTypes>b__33_1(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   --- End of inner exception stack trace ---
   at System.ThrowHelper.ThrowAggregateException(List`1 exceptions)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at StructureMap.PluginGraphBuilder.RunConfigurations()
   at StructureMap.PluginGraphBuilder.RunConfigurations()
   at StructureMap.PipelineGraph.Configure(Action`1 configure)
   at StructureMap.Container.Configure(Action`1 configure)
   at Grips.IocContainer.IocFactory.Initialise(String[] givenPath)
   at Grips.Bootstrapper.ApplicationStarter.Start()
   at Grips.Bootstrapper.ApplicationStarter.Run()
---> (Inner Exception #0) System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
   at StructureMap.TypeRules.TypeExtensions.IsConcrete(Type type)
   at StructureMap.TypeRules.TypeExtensions.<rawFindInterfacesThatCloses>d__16.MoveNext()
   at StructureMap.TypeRules.TypeExtensions.<rawFindInterfacesThatCloses>d__16.MoveNext()
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at StructureMap.Graph.GenericConnectionScanner.<ScanTypes>b__5_0(Type type)
   at StructureMap.StringExtensions.Each[T](IEnumerable`1 enumerable, Action`1 action)
   at StructureMap.Graph.GenericConnectionScanner.ScanTypes(TypeSet types, Registry registry)
   at StructureMap.StringExtensions.Each[T](IEnumerable`1 enumerable, Action`1 action)
   at StructureMap.Graph.AssemblyScanner.<ScanForTypes>b__33_1(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)<---

---> (Inner Exception #1) System.ArgumentNullException: Value cannot be null.
Parameter name: type
   at System.Reflection.IntrospectionExtensions.GetTypeInfo(Type type)
   at StructureMap.TypeRules.TypeExtensions.IsConcrete(Type type)
   at StructureMap.TypeRules.TypeExtensions.<rawFindInterfacesThatCloses>d__16.MoveNext()
   at StructureMap.TypeRules.TypeExtensions.<rawFindInterfacesThatCloses>d__16.MoveNext()
   at System.Linq.Enumerable.DistinctIterator`1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at StructureMap.Graph.GenericConnectionScanner.<ScanTypes>b__5_0(Type type)
   at StructureMap.StringExtensions.Each[T](IEnumerable`1 enumerable, Action`1 action)
   at StructureMap.Graph.GenericConnectionScanner.ScanTypes(TypeSet types, Registry registry)
   at StructureMap.StringExtensions.Each[T](IEnumerable`1 enumerable, Action`1 action)
   at StructureMap.Graph.AssemblyScanner.<ScanForTypes>b__33_1(Task`1 t)

```

**Comment by stvndall** [comment]
This was 100%  my problem. It was the way I scan scanning depenendant assemblies, and creating the tree. It was going out of my controllable scope. And there must be interesting things happening in there.

~closed
