### ISSUE TITLE
Concurrent resolving of same PluginType

### ISSUE THREAD

**Issue by sm-g** [structuremap/structuremap#646]
I have `Task.WhenAll(tasks)`, and each task uses AutoMapper's ValueResolver which has dependency, resolved via DI.

```
public AutoMapperRegistry()
        {
            ForSingletonOf<MapperConfiguration>().Use("Build AutoMapper config", ctx =>
            {
                var profiles = ctx.GetAllInstances<Profile>();
                var config = new MapperConfiguration(cfg =>
                {
                    cfg.AllowNullCollections = true;

                    foreach (var profile in profiles)
                    {
                        cfg.AddProfile(profile);
                    }
                });
                return config;
            });
            For<IMapper>().Use(ctx => ctx.GetInstance<MapperConfiguration>().CreateMapper(ctx.GetInstance));
        }
```

When AutoMapper creates ValueResolver instance, same dependency added to dictionary more than once:

```
System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at StructureMap.SessionCache.GetDefault(Type pluginType, IPipelineGraph pipelineGraph)
   at AutoMapper.MappingOperationOptions`2.CreateInstance[T]()
```

Looks like expcetion from https://github.com/structuremap/structuremap/blob/master/src/StructureMap/SessionCache.cs#L77

**Comment by rheone** [comment]
I know it is little solace, but I encountered this issue earlier today, and within a few hours I was able to convert my multi-tiered application to use [Lamar](https://jasperfx.github.io/lamar/), the successor to StructureMap, with out too much difficulty. 

So far the issue appears to be fixed.

**Comment by wr-cdargis** [comment]
For any future people running into this problem I noticed that we saw this race condition pop up as we approached maximum memory usage.
